### ISSUE TITLE
Add write-up to explain ROS WSL setup

### ISSUE THREAD

**Issue by aidanwoodcu** [ARDVARC/ARDVARC#5]
There is already [a write-up explaining how to set up ROS](../blob/main/ROS.md), but it suggests VMWare which is gross considering that WSL exists. This issue is to do a similar write-up but for WSL. It probably isn't worthwhile but I might anyways.

**Comment by joda2486** [comment]
I am not familiar with WSL so I would not be able to do the write up but if you want to feel free.
